# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""E2E tests for HyperCLOVAX-SEED-Omni-8B.

Tests cover:
  - Text-only inference (comprehension)
  - Speech-to-Speech  (audio input → audio output)
  - Text-to-Vision    (text input  → image output)
  - Audio-to-Vision   (audio input → image + audio output)
"""
from pathlib import Path

import pytest

from tests.conftest import (
    generate_synthetic_audio,
    generate_synthetic_image,
    modify_stage_config,
)
from tests.utils import hardware_test
from vllm_omni.platforms import current_omni_platform

MODEL = "naver-hyperclovax/HyperCLOVAX-SEED-Omni-8B"

_CI_YAML = str(
    Path(__file__).parent.parent / "stage_configs" / "hcx_omni_ci.yaml"
)


def _ci_config(enforce_eager: bool = True) -> str:
    updates: dict = {
        "stage_args": {
            0: {"engine_args.enforce_eager": str(enforce_eager).lower()},
        }
    }
    return modify_stage_config(_CI_YAML, updates=updates)


stage_config = _ci_config(enforce_eager=True)
test_params = [(MODEL, stage_config)]


# ------------------------------------------------------------------ #
# Helper                                                               #
# ------------------------------------------------------------------ #

def _text_prompt(text: str) -> dict:
    return {
        "role": "user",
        "content": [{"type": "text", "text": text}],
    }


def _audio_text_prompt(audio_array, text: str) -> dict:
    return {
        "role": "user",
        "content": [
            {"type": "input_audio", "input_audio": {"data": audio_array, "format": "wav"}},
            {"type": "text", "text": text},
        ],
    }


def _image_text_prompt(image_array, text: str) -> dict:
    return {
        "role": "user",
        "content": [
            {"type": "image_url", "image_url": {"url": image_array}},
            {"type": "text", "text": text},
        ],
    }


# ------------------------------------------------------------------ #
# Tests                                                                #
# ------------------------------------------------------------------ #

@pytest.mark.advanced_model
@pytest.mark.omni
@hardware_test(
    res={"cuda": "L4"},
    num_cards={"cuda": 3},
)
@pytest.mark.parametrize("omni_runner", test_params, indirect=True)
def test_text_to_text(omni_runner, omni_runner_handler) -> None:
    """Text-only (comprehension) request — verifies thinker stage alone."""
    request_config = {
        "prompts": "What is the capital of South Korea?",
        "output_modalities": ["text"],
    }
    results = omni_runner.run(request_config)
    assert results and len(results) > 0


@pytest.mark.advanced_model
@pytest.mark.omni
@hardware_test(
    res={"cuda": "L4"},
    num_cards={"cuda": 3},
)
@pytest.mark.parametrize("omni_runner", test_params, indirect=True)
def test_audio_to_audio(omni_runner, omni_runner_handler) -> None:
    """Speech-to-Speech: audio input processed by thinker → audio decoder."""
    audio = generate_synthetic_audio(1, 1, 16000)["np_array"]
    if len(audio.shape) == 2:
        audio = audio.squeeze()

    request_config = {
        "prompts": _audio_text_prompt(audio, "Repeat what you heard."),
        "output_modalities": ["text", "audio"],
    }
    results = omni_runner.run(request_config)
    assert results and len(results) > 0


@pytest.mark.advanced_model
@pytest.mark.omni
@hardware_test(
    res={"cuda": "L4"},
    num_cards={"cuda": 3},
)
@pytest.mark.parametrize("omni_runner", test_params, indirect=True)
def test_text_to_image(omni_runner, omni_runner_handler) -> None:
    """Text-to-Vision: text prompt → image generated by vision decoder."""
    request_config = {
        "prompts": "Draw a picture of a cat sitting on a sofa.",
        "output_modalities": ["text", "image"],
    }
    results = omni_runner.run(request_config)
    assert results and len(results) > 0


@pytest.mark.advanced_model
@pytest.mark.omni
@hardware_test(
    res={"cuda": "L4"},
    num_cards={"cuda": 3},
)
@pytest.mark.parametrize("omni_runner", test_params, indirect=True)
def test_image_to_text(omni_runner, omni_runner_handler) -> None:
    """Image understanding: image input → text description."""
    image = generate_synthetic_image(224, 224)["np_array"]
    request_config = {
        "prompts": _image_text_prompt(image, "Describe this image."),
        "output_modalities": ["text"],
    }
    results = omni_runner.run(request_config)
    assert results and len(results) > 0


@pytest.mark.advanced_model
@pytest.mark.omni
@hardware_test(
    res={"cuda": "L4"},
    num_cards={"cuda": 3},
)
@pytest.mark.parametrize("omni_runner", test_params, indirect=True)
def test_multimodal_to_multimodal(omni_runner, omni_runner_handler) -> None:
    """Full omni: audio + image input → text + audio + image output."""
    audio = generate_synthetic_audio(1, 1, 16000)["np_array"]
    if len(audio.shape) == 2:
        audio = audio.squeeze()

    request_config = {
        "prompts": "Listen to the audio and draw what you hear.",
        "output_modalities": ["text", "audio", "image"],
    }
    results = omni_runner.run(request_config)
    assert results and len(results) > 0
